# Generated by Django 3.1.1 on 2020-09-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20200914_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
