# Generated by Django 3.1.1 on 2020-09-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_tag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
